oban: <http://purl.org/oban/>
gwas_cytogenetic_region: <http://rdf.ebi.ac.uk/dataset/gwas/CytogeneticRegion/>
gwas_snp: <http://rdf.ebi.ac.uk/dataset/gwas/SingleNucleotidePolymorphism/>
gwas_trackable: <http://rdf.ebi.ac.uk/dataset/gwas/Trackable/>
gwas: <http://rdf.ebi.ac.uk/terms/gwas/>
efo: <http://www.ebi.ac.uk/efo/>
ro: <http://www.obofoundry.org/ro/ro.owl#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>