sparql:
  description: Obtain SNP and GWAS association records from the GWAS-Catalog data. 
  variables: [GwasSnp, gwas_assosiation]

stanza_sparql:
  description: Obtain a SNP and GWAS association record from the GWAS-Catalog data. 
  parameters:
    rs: "rs2896103"  
  variables: [rs, bp_position, gwas_cytogenetic_region, gwas_trait_name, p_value, pubmed_id, gwas_association_parent, gwas_association_child, association_description]
