title: NLM Catalog
website: https://www.ncbi.nlm.nih.gov/nlmcatalog/
description: NLM bibliographic data on journals, books, audiovisual materials, computer software, electronic resources, and other materials
tags: [ Ontology/Terminology/Nomenclature, Journal article/Report/Bibliography ]
provider: National Library of Medicine 
rdf_provider: Database Center for Life Science
version: 
issued: 2025-06-30
license:
  - name:                              
  - url: 
  - credit: 
