mesh: <http://id.nlm.nih.gov/mesh/>
ggdsch: <http://jcggdb.jp/rdf/diseases/gdgdb-schema#>
ggdont: <http://jcggdb.jp/rdf/diseases/ggdonto-schema#>
gmschema: <http://jcggdb.jp/rdf/diseases/gmncbi-schema#>
paconto: <http://jcggdb.jp/rdf/diseases/paconto#>
pacsch: <http://jcggdb.jp/rdf/diseases/paconto-schema#>
glycan: <http://purl.jp/bio/12/glyco/glycan#>
glyc: <http://purl.jp/bio/12/glyco/glycan/>
up: <http://purl.uniprot.org/core/>
taxo: <http://purl.uniprot.org/taxonomy/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
skos: <http://www.w3.org/2004/02/skos/core#>