title: PubChem RDF
website: https://pubchem.ncbi.nlm.nih.gov/
description: PubChem is an open chemistry database at the National Institutes of Health (NIH). For the detailed information, please see the following URL\: https\://pubchemdocs.ncbi.nlm.nih.gov/about. \Note\: The endpoint does not include files provided at ftp\://ftp.ncbi.nlm.nih.gov/pubchem/RDF/compound/nbr2d/ and ftp\://ftp.ncbi.nlm.nih.gov/pubchem/RDF/compound/nbr3d/\
tags: [ Drug/Chemical, Other biomolecule]
provider: National Center for Biotechnology Information
rdf_provider: National Center for Biotechnology Information
version:
issued: 2025-05-28
license:
  - name:                              
  - url: https://www.ncbi.nlm.nih.gov/home/about/policies/
  - credit: 
