- Sample sample:s_18:
  - a:
    - sio:SIO_001050
    - kero:SampleType
  - kero:cellLine:
    - cellline: efo:EFO_0003140
  - snomedct:specimenOf:
    - person:
      - []:
        - a: foaf:Person
        - foaf:gender:
          - gender: "Male"
        - dbpedia:age:
          - age: 48
        - kero:ethnicity:
          - ethnicity: snomed:414551003
        - kero:smokingStatus:
          - smoking_status: snomed:77176002
  - obo:RO_0002162:
    - taxonomy: taxonomy:9606
  - dct:identifier:
    - id: "s_18"
  - rdfs:label:
    - label: "LC2/AD"
  - skos:altLabel:
    - alt_label: ""

- Region hg38:1:11210-11210:
  - a: faldo:Region
  - faldo:begin:
    - position: Position
  - faldo:end:
    - position: Position
  - faldo:reference:
    - reference: Reference
  - rdfs:label:
    - label: "hg38 chromosome 1:11210-11210"
  - skos:exactMatch+:
    - exact_match: grch38:1:11210-11210:1

- Reference hg38:1:
  - a: obo:SO_0000957
  - rdfs:label:
    - label: "hg38 chromosome 1"
  - skos:exactMatch:
    - exact_match: grch38:1

- Position hg38:1:11210:
  - a:
    - faldo:ExactPosition
    - faldo:StrandedPosition
  - faldo:reference:
    - reference: Reference
  - rdfs:label:
    - label: "hg38 chromosome 1:11210"
  - faldo:position:
    - position: 11210
  - skos:exactMatch:
    - exact_match: grch38:1:11210:1

- Bs-seqDataset bsseqdataset:bs_data_9606_LC2ad:
  - a: kero:MethylseqDataset
  - kero:hasMethylationSite+:
    - methylated_dna_base_feature: Bs-seqData
  - kero:sample:
    - sample: Sample # LC2/AD
  - rdfs:label:
    - label: "kero BS-seq dataset of LC2/AD"
  - dcat:theme:
    - species: species:9606 # Homo sapiens

- Bs-seqData bsseqdata:bs_data_9606_LC2ad_1:
  - a: obo:SO_0000306
  - faldo:location+:
    - region: Region
    - position: Position
  - kero:bin:
    - bin: 1
  - kero:caNum:
    - canum: 2
  - kero:cgNum:
    - cgnum: 3
  - dct:identifier:
    - id: "bs_data_9606_LC2ad_1"
  - rdfs:label:
    - label: "Methylation site of LC2ad on chromosome 1:11210"

- Chip-seqDataset chipseqdataset:chip_inf_9606_LC2ad_H3K4me3:
  - a: kero:ChIPseqDataset
  - kero:antibodyFor:
    - antibodyfor: "H3K4me3"
  - kero:hasBindingSite+:
    - chipseqdata: Chip-seqData
  - kero:sample:
    - sample: Sample
  - rdfs:label:
    - label: "kero BS-seq dataset of LC2/AD (H3K4me3)"
  - dcat:theme:
    - species_type: species:9606 # Homo sapiens

- Chip-seqData chipseqdata:chip_inf_9606_chr22_LC2ad_H3K4me3_1:
  - a: obo:SO_0001697
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 3
  - kero:count:
    - count: 1
  - dct:identifier:
    - id: "chip_inf_9606_chr22_LC2ad_H3K4me3_1"
  - rdfs:label:
    - label: "H3K4me3 biding site of LC2ad on chromosome 22:15284452-15284731"

- ChromhmmDataset chromhmmdataset:chromhmm_inf_9606_LC2ad:
  - a: kero:ChromHMMDataset
  - kero:hasChromHMM+:
    - strong_enhancer: StrongEnhancer
    - weak_enhancer: WeakEnhancer
    - inactive_region: InactiveRegion
    - active_promoter: ActivePromoter
    - weak_or_poised_promoter: WeakOrPoisedPromoter
    - low_or_no_signal: LowOrNoSignal
    - transcriptional_elongation: TranscriptionalElongation
    - inactive_region_or_heterochroma: InactiveRegionOrHeterochroma
  - kero:sample:
    - sample: Sample
  - rdfs:label:
    - label: "kero ChromHMM dataset of LC2/AD"
  - dcat:theme:
    - species_type: species:9606 # Homo sapiens

- StrongEnhancer chromhmmdata:chromhmm_inf_9606_LC2ad_495479:
  - a: kero:StrongEnhancer
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- WeakEnhancer chromhmmdata:chromhmm_inf_9606_LC2ad_495480:
  - a: kero:WeakEnhancer
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- InactiveRegion chromhmmdata:chromhmm_inf_9606_LC2ad_495600:
  - a: kero:InactiveRegion
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- ActivePromoter chromhmmdata:chromhmm_inf_9606_LC2ad_495517:
  - a: kero:ActivePromoter
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- WeakOrPoisedPromoter chromhmmdata:chromhmm_inf_9606_LC2ad_495509:
  - a: kero:WeakOrPoisedPromoter
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- LowOrNoSignal chromhmmdata:chromhmm_inf_9606_LC2ad_495487:
  - a: kero:LowOrNoSignal
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- TranscriptionalElongation chromhmmdata:chromhmm_inf_9606_LC2ad_495489:
  - a: kero:TranscriptionalElongation
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- InactiveRegionOrHeterochroma chromhmmdata:chromhmm_inf_9606_LC2ad_495576:
  - a: kero:InactiveRegionOrHeterochroma
  - faldo:location:
    - region: Region
  - kero:bin:
    - bin: 10
  - dct:identifier:
    - id: "chromhmm_inf_9606_LC2ad_1"
  - rdfs:label:
    - label: "ChromHMM site of LC2ad on chromosome 1:265249-265649"

- Rna-seqDataset rnaseqdataset:rnaseq_qty_9606_LC2ad:
  - a: kero:RNAseqDataset
  - kero:hasExpressionData+:
    - rna_seq_data: Rna-seqData
  - kero:sample:
    - sample: Sample
  - rdfs:label:
    - label: "kero RNA-seq dataset of LC2/AD"
  - dcat:theme:
    - species_type: species:9606 # Homo sapiens

- Rna-seqData rnaseqdata:rnaseq_qty_9606_LC2ad_1:
  - a: obo:SO_0000673
  - faldo:location:
    - location: Region
  - kero:count:
    - count: 504
  - kero:gene+:
    - ncbigene: ncbigene:57573 # 57573
    - refseq: refseq:NM_020813
  - kero:ppm:
    - ppm: 11.54
  - kero:rpkm:
    - rpkm: 2.32
  - dct:identifier:
    - id: "rnaseq_qty_9606_LC2ad_1"
  - rdfs:label:
    - label: "RNA-seq of LC2ad on chromosome 19:56507843-56528900"
  - skos:altLabel+:
    - alt_label: "NM_020813"

- SnvDataset snvdataset:vcf_inf_9606_LC2ad:
  - a: kero:SNVDataset
  - kero:hasVariationSite+:
    - snvdata: SnvData
  - kero:sample:
    - sample: Sample
  - rdfs:label:
    - label: "kero SNV dataset of LC2/AD"
  - dcat:theme:
    - species_type: species:9606 # Homo sapiens

- SnvData snvdata:vcf_inf_9606_chr22_LC2ad_1:
  - a: obo:SO_0001483
  - faldo:location+:
    - region: Region
    - position: Position
  - kero:additionalInformation:
    - additional_information: "AC=1;AF=0.50;AN=2;BaseQRankSum=1.056;DB;DP=32;Dels=0.00;FS=5.969;HRun=5;HaplotypeScore=0.0000;MQ=37.26;MQ0=3;MQRankSum=-0.427;QD=6.85;ReadPosRankSum=0.607;SB=-54.16"
  - kero:alleleFrequency:
    - allele_frequency: 0.5
  - kero:allelicDepth:
    - allelic_depth: "21,11"
  - kero:genotype:
    - genotype: "0/1"
  - kero:genotypeData:
    - genotype_data: "GT:AD:DP:GQ:PL|0/1:21,11:32:99:249,0,519"
  - kero:genotypeQuality:
    - genotype_quality: 99.0
  - kero:snp:
    - dbsnp: dbsnp:rs183011531
  - dct:identifier:
    - id: "vcf_inf_9606_chr22_LC2ad_1"
  - ensemblevariation:has_allele+:
    - allele1: hg38:22:15282081#T
    - allele2: hg38:22:15282081#G
  - rdfs:label:
    - label: "Variation site of LC2ad on chromosome 22:15282081"

- Tss-seqDataset tssseqdataset:tss_bincount_9606_LC2ad:
  - a: kero:TSSseqDataset
  - kero:hasTranscriptionStartSite+:
    - tss: tssseqdata:tss_bincount_9606_chr2_LC2ad_29457 # TSS site of LC2ad on chromosome 2:174248527
  - kero:sample:
    - sample: Sample
  - rdfs:label:
    - label: "kero TSS-seq dataset of LC2/AD"
  - dcat:theme:
    - species_type: species:9606 # Homo sapiens

- Tss-seqData tssseqdata:tss_bincount_9606_chr22_LC2ad_1:
  - a: obo:SO_0000315
  - faldo:location+:
    - region: Region
    - position: Position
  - kero:bin:
    - bin: 1
  - kero:count:
    - count: 3
  - kero:rep:
    - rep: 0
  - kero:repgrp:
    - repgrp: 23426
  - kero:repprm:
    - repprm: 3
  - dct:identifier:
    - id: "tss_bincount_9606_chr22_LC2ad_1"
  - rdfs:label:
    - label: "TSS site of LC2ad on chromosome 22:16601352"

