- PubMed pubmed:10075408:
  - a: sio:SIO_000154 
  - prism:ISSN:
    - issn_number: "1350-0872"
  - prism:doi:
    - doi_number: "10.1099/13500872-145-2-279"
  - prism:endingPage:
    - ending_page: "281"
  - prism:publicationName:
    - journal_name: "Microbiology (Reading, England)"
  - prism:startingPage:
    - starting_page: "279"
  - dct:created+:
    - created_date: "1999-3-13"
  - dct:creator:
    - []:
      - a: olo:OrderedList
      - olo:length:
        - num_of_authors: 2
      - olo:slot+:
        - []:
          - olo:index:
            - index_number: 1
          - olo:item:
            - []:
              - a: foaf:Person
              - foaf:LastName:
                - last_name: "Faguy"
              - foaf:firstName:
                - first_name: "D M"
              - foaf:name:
                - full_name: "Faguy DM"
  - dct:identifier:
    - pubmed_id: "10075408"
  - dct:issued:
    - date_of_issued: 1999-02-01
  - dct:language:
    - language: "eng"
  - dct:source:
    - journal_volume_page: "Microbiology. 1999-02;145 ( Pt 2)():279-281."
  - dct:title:
    - article_title: "A twisted tale: the origin and evolution of motility and chemotaxis in prokaryotes."
  - bibo:pmid:
    - pubmed_id: "10075408"
  - bibo:volume:
    - volume_number: "145 ( Pt 2)"
  - pav:derivedFrom:
    - node_15: "NLM"
  - fabio:dateLastUpdated:
    - last_update_date: "2019-12-16"
  - fabio:hasIssnL:
    - issnl_number: "1350-0872"
  - fabio:hasNLMJournalTitleAbbreviation:
    - nlm_title_abbrev: "Microbiology"
  - fabio:hasNationalLibraryOfMedicineJournalId:
    - nlm_journal_id: "9430468"
  - fabio:hasPlaceOfPublication:
    - place_of_publication: "England"
  - pubmedontology:dp:
    - date_of_issued: "1999 Feb"

