title: Gene Ontology
website: http://geneontology.org/
description: description: The Gene Ontology resource provides a computational representation of our current scientific knowledge about the functions of genes (or, more properly, the protein and non-coding RNA molecules produced by genes) from many different organisms, from humans to bacteria.
tags: []
provider:
creators:
  - name: Name 1
    affiliation: Affiliation 1
  - name: Name 2
    affiliation: Affiliation 2
version: 2020-01-01
issued: 2020-01-01
licenses:
  - Attribution 4.0 International (CC BY 4.0) 
