rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
schema: <https://purl.dsmz.de/schema/>
mediadive: <https://purl.dsmz.de/mediadive/medium/>
solution: <https://purl.dsmz.de/mediadive/solution/>
solution_recipe: <https://purl.dsmz.de/mediadive/solution_recipe/>
gas: <https://purl.dsmz.de/mediadive/gas/>
equipment: <https://purl.dsmz.de/mediadive/equipment/>
ingredient: <https://purl.dsmz.de/mediadive/ingredient/>
strain: <https://purl.dsmz.de/mediadive/strain/>
growth: <https://purl.dsmz.de/mediadive/growth/>
medium_composition: <https://purl.dsmz.de/mediadive/medium_composition/>
step: <https://purl.dsmz.de/mediadive/step/>
solution_recipe: <https://purl.dsmz.de/mediadive/solution_recipe/>
modification: <https://purl.dsmz.de/mediadive/modification/>
modification_detail: <https://purl.dsmz.de/mediadive/modification_detail/>
gas: <https://purl.dsmz.de/mediadive/gas/>
