title: ChEBI RDF
website: https://www.ebi.ac.uk/chebi/
description: ChEBI（Chemical Entities of Biological Interest） は、「小分子化合物」を対象とした、自由にアクセス可能なオントロジーベースのデータベースです。化学構造、名称、定義、機能的役割、生物学的な関係性などを含む手作業でキュレーションされた非専有データを提供し、外部リソースへのリンクも備えており、ケミカルバイオロジーやバイオインフォマティクス分野で広く利用されています
tags: [ Drug/Chemical ]
provider: European Bioinformatics Institute
creators:
  - name: European Bioinformatics Institute
version: Release 242
issued: 2025-06-02
licenses:
  - Creative Commons License (CC BY 4.0), and governed by EMBL-EBI’s terms of use and Long-term data preservation policy.
