rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
oboinowl: <http://www.geneontology.org/formats/oboInOwl#>
obo: <http://purl.obolibrary.org/obo/>
obochebi: <http://purl.obolibrary.org/obo/chebi/>
obochebi_sha: <http://purl.obolibrary.org/obo/chebi#>
obochebi_dot: <http://purl.obolibrary.org/obo/chebi.>
owl: <http://www.w3.org/2002/07/owl#>
