- Nando nando:1200004:
    - a: owl:Class
    - rdfs:label:
        - label_ja: '"脊髄性筋萎縮症 I 型"@ja'
    - rdfs:label*:
        - label_en: '"Werdnig-Hoffmann disease"@en'
    - rdfs:label?:
        - label_hira: '"せきずいせいきんいしゅくしょう 1がた"@ja-Hira'
    - dct:identifier:
        - nando_id: "1200004"
    - nando:hasNotificationNumber?:
        - notification_number: "3"
    - dct:source?: 
        - source: <https://www.nanbyou.or.jp/wp-content/uploads/upload_files/File/003-201704-kojin.pdf>
    - rdfs:seeAlso*:
        - see_also: <https://www.nanbyou.or.jp/entry/135>
    - skos:closeMatch*: 
        - close_match: mondo:0009669
    - skos:prefLabel:
        - pref_label?: '"脊髄性筋萎縮症 I 型"@ja'
    - skos:altLabel*:
        - alt_label_ja: '"ウェルドニッヒ・ホフマン病"@ja'
    - skos:altLabel*:
        - alt_label_en: '"Werdnig-Hoffmann disease"@en'
    - dct:description?:
        - description: '"脊髄性筋萎縮症（spinal muscular atrophy：SMA）は、脊髄の前角細胞の変性による筋萎縮と進行性筋力低下を特徴とする下位運動ニューロン病である。上位運動ニューロン徴候は伴わない。体幹、四肢の近位部優位の筋力低下、筋萎縮を示す。発症年齢、臨床経過に基づき、I型、II型、III型、IV型に分類される。I、II型の95％にSMN1遺伝子欠失が認められ、III型の約半数、IV型の１～２割においてSMN１遺伝子変異を認める。SMN1遺伝子に変異がなく早期に呼吸障害を来すI型において、IGHMBP2の遺伝子変異を認めることがある。"@ja'

