- HGNC hgnc:11998:
  - a: m2r:Gene
  - rdfs:label:
    - gene: "TP53"
  - dct:description:
    - label: "tumor protein p53"
  - rdfs:seeAlso:
#    - see_also: <http://identifiers.org/ncbigene/7157>, <http://identifiers.org/ensembl/ENSG00000141510>, <http://identifiers.org/refseq/NM_000546>, <http://identifiers.org/uniprot/P04637>, <http://identifiers.org/omim/191170>
    - see_also: [ NCBIGene, Ensembl, RefSeq, UniProt, OMIM ]
  - dct:references*:
    - reference: <http://identifiers.org/pubmed/20498374>
  - skos:altLabel*:
    - alt_label: "p53"

- NCBIGene <http://identifiers.org/ncbigene/7157>:
  - a: ido:NCBIGene
  - rdfs:label:
    - ncbigene_id: 7157

- Ensembl <http://identifiers.org/ensembl/ENSG00000141510>:
  - a: ido:Ensembl
  - rdfs:label:
    - ensembl_id: ENSG00000141510

- RefSeq <http://identifiers.org/refseq/NM_000546>:
  - a: ido:RefSeq
  - rdfs:label:
    - refseq_id: NM_000546

- UniProt <http://identifiers.org/uniprot/P04637>:
  - a: ido:UniProt
  - rdfs:label:
    - uniprot_id: P04637

- OMIM <http://identifiers.org/omim/191170>:
  - a: ido:OMIM
  - rdfs:label:
    - omim_id: 191170


