rdfs: <http://www.w3.org/2000/01/rdf-schema#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
ndfrt: <http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#>
ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
sio: <http://semanticscience.org/resource/>
#cheminf: <http://semanticscience.org/resource/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
bao: <http://www.bioassayontology.org/bao#>
bp: <http://www.biopax.org/release/biopax-level3.owl#>
cito: <http://purl.org/spar/cito/>
fabio: <http://purl.org/spar/fabio/>
dcterms: <http://purl.org/dc/terms/>
foaf: <http://xmlns.com/foaf/0.1/>

# pubchem
vocab: <http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>
biosystem: <http://rdf.ncbi.nlm.nih.gov/pubchem/biosystem/>
compound: <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
descr: <http://rdf.ncbi.nlm.nih.gov/pubchem/descriptor/>
source: <http://rdf.ncbi.nlm.nih.gov/pubchem/source/>
syno: <http://rdf.ncbi.nlm.nih.gov/pubchem/synonym/>
bioassay: <http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay/>
pathway: <http://rdf.ncbi.nlm.nih.gov/pubchem/pathway/>
protein: <http://rdf.ncbi.nlm.nih.gov/pubchem/protein/>
gene: <http://rdf.ncbi.nlm.nih.gov/pubchem/gene/>
conserveddomain: <http://rdf.ncbi.nlm.nih.gov/pubchem/conserveddomain/>
measuregroup: <http://rdf.ncbi.nlm.nih.gov/pubchem/measuregroup/>
reference: <http://rdf.ncbi.nlm.nih.gov/pubchem/reference/>
concept: <http://rdf.ncbi.nlm.nih.gov/pubchem/concept>
inchikey: <http://rdf.ncbi.nlm.nih.gov/pubchem/inchikey/>
# uniprot
uniprotcore: <https://www.uniprot.org/core/>
uniprot: <<http://purl.uniprot.org/uniprot/>
# ensemnbl
ensembl: <http://rdf.ebi.ac.uk/resource/ensembl/>
# PAV ontology: provenance, authoring and versioning
pav: <http://purl.org/pav/>
# MeSH
mesh: <http://id.nlm.nih.gov/mesh/>
# Taxonomy
taxonomy: <http://identifiers.org/taxonomy/>
# pdb
pdb: <http://rdf.wwpdb.org/pdb/>
pdbo: <http://rdf.wwpdb.org/schema/pdbx-v40.owl#>
#wikidata
wikidata: <http://www.wikidata.org/entity/>
