sparql:
  description: Obrain short genetic valiations from dbSNP
  subject: dbSNPValiation
  variables:
    - identifier
    - build
    - reference
    - position
    - reference_allele
    - allele

stanza:
  description: Obrain short genetic valiations from dbSNP
  subject: dbSNPValiation
  parameters:
    identifier: rs1000017372
  variables:
    - build
    - reference
    - position
    - reference_allele
    - allele
