dct: <http://purl.org/dc/terms/>
medgen: <http://www.ncbi.nlm.nih.gov/medgen/>
mo: <http://med2rdf/ontology/medgen#>
mo_ispref: <http://med2rdf/ontology/medgen/ispref#>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
sty: <http://purl.bioontology.org/ontology/STY/>
ncbigene: <http://identifiers.org/ncbigene/>
ncbigeneo: <https://dbcls.github.io/ncbigene-rdf/ontology.ttl#>
taxonomy: <http://identifiers.org/taxonomy/>
obo: <http://purl.obolibrary.org/obo/>
