- INstruct ins:Q05513-PF00130_Q05513-PF00069:
  - a: bp3:MolecularInteraction
  - bp3:dataSource:
    - data_source: <http://instruct.yulab.org/>
  - bp3:displayName:
    - display_hame: '"Q05513-Q05513"^^xsd:string'
  - bp3:evidence+:
    - evidence: pint:evidence_pubmed_11078718_ , pint:evidence_pubmed_15665819_ , pint:evidence_pubmed_17203073_ , pint:evidence_pubmed_18650932_ , pint:evidence_pubmed_19920073_ , pint:evidence_pubmed_21900206_ , pint:evidence_pubmed_21911421_ , pint:evidence_pubmed_9748166_ , pint:evidence_pdb_3pfq_false
  - bp3:name:
    - name: '"Q05513-Q05513"^^xsd:string'
  - bp3:participant:
    - []:
      - obo:BFO_0000051:
        - pair0: uni:Q05513
        - pair1: pfm:PF00130
#    - []:
#      - obo:BFO_0000051:
#        - pair0: uni:Q05513
#        - pair1: pfm:PF00069
