rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
dc: <http://purl.org/dc/elements/1.1/>
foaf: <http://xmlns.com/foaf/0.1/>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
faldo: <http://biohackathon.org/resource/faldo#>
hco: <http://identifiers.org/hco/>
hgnc: <http://identifiers.org/hgnc/>
so: <http://purl.obolibrary.org/obo/so#>
dbsnp: <http://identifiers.org/dbsnp/>
ensembl: <http://rdf.ebi.ac.uk/terms/ensembl/>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
ensembl_id: <http://identifiers.org/ensembl/>
m2r: <http://med2rdf.org/ontology/med2rdf#>
tgvo: <http://togovar.biosciencedbc.jp/vocabulary/>
clinvar: <http://ncbi.nlm.nih.gov/clinvar/variation/>
