- Mondo obo:MONDO_0020680:
  - a: owl:Class
  - rdfs:subClassOf+:
    - sub_class: obo:MONDO_0020683
  - rdfs:label:
    - label: "acute bronchiolitis"
  - obo:IAO_0000115?:
    - definition: "Acute inflammation of the bronchioles usually caused by the respiratory syncytial virus."
  - oboinowl:hasDbXref+:
    - database_cross_reference: "NCIT:C39659"
  - oboinowl:hasExactSynonym+:
    - has_exact_synonym: "acute bronchiolitis"
  - oboinowl:hasRelatedSynonym+:
    - synonyms: "acute Bronchiolitis"
  - oboinowl:id:
    - id: "MONDO:0020680"
  - skos:exactMatch+:
    - exact_match: obo:NCIT_C39659
