oboinowl: <http://www.geneontology.org/formats/oboInOwl#>
obo: <http://purl.obolibrary.org/obo/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
skos: <http://www.w3.org/2004/02/skos/core#>