- ClinVarAnnotaions clinvar:209597:
  - a: cvo:VariationArchiveType
  - rdfs:label:
    - title: NM_000059.3(BRCA2):c.-764A>G
  - cvo:accession:
    - vcv: VCV000209597
  - cvo:interpreted_record:
    - []:
      - cvo:review_status:
        - review_status: reviewed by expert panel
      - cvo:rcv_list:
        - []:
          - cvo:rcv_accession:
            - []:
              - cvo:interpretation:
                - interpretation: Benign
              - cvo:date_last_evaluated:
                - last_evaluated: 2015-01-12
              - cvo:interpreted_condition:
                - []:
                  - cvo:type_rcv_interpreted_condition:
                    - condition: Breast-ovarian cancer, familial 2
                  - cvo:db*:
                    - db: MedGen
                  - cvo:id*:
                    - id: C2675520
      - cvo:simple_allele:
        - []:
          - cvo:location:
            - []:
              - faldo:location:
                - []:
                  - a: faldo:ExactPosition, cvo:SequenceLocation
                  - faldo:position:
                    - position: "32889080"
                  - faldo:reference:
                    - reference: <http://identifiers.org/hco/13#GRCh37>, <http://identifiers.org/refseq/NC_000013.10>
