rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
faldo: <http://biohackathon.org/resource/faldo#>
obo: <http://purl.obolibrary.org/obo/>
so: <http://purl.obolibrary.org/obo/so#>
dc: <http://purl.org/dc/elements/1.1/>
dcterms: <http://purl.org/dc/terms/>
owl: <http://www.w3.org/2002/07/owl#>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
terms: <http://rdf.ebi.ac.uk/terms/ensembl/>
ense: <http://rdf.ebi.ac.uk/resource/ensembl.exon/>
ensp: <http://rdf.ebi.ac.uk/resource/ensembl.protein/>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
ensgloss: <http://ensembl.org/glossary/>
ensi: <http://identifiers.org/ensembl/>
taxonomy: <http://identifiers.org/taxonomy/>
uniprot: <http://purl.uniprot.org/uniprot/>
sio: <http://semanticscience.org/resource/>
skos: <http://www.w3.org/2004/02/skos/core#>
uniprot: <http://purl.uniprot.org/uniprot/>
