title: BioSample RDF
website: https://ddbj.nig.ac.jp/
description: BioSample RDF developed by DBCLS and distributed by DDBJ
tags: []
provider: Bioinformation and DDBJ Center
creators:
  - name: Tazro Ohta
    affiliation: Database Center for Life Science
  - name: Shuya Ikeda
    affiliation: Database Center for Life Science
  - name: Shuichi Kawashima
    affiliation: Database Center for Life Science
  - name: Takatomo Fujisawa
    affiliation: Bioinformation and DDBJ Center
version: 20200903-1443
issued: 2020-09-03
licenses:
  - Attribution 4.0 International (CC BY 4.0)
