rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
xsi: <http://www.w3.org/2001/XMLSchema-instance>
pdbx: <http://pdbml.pdb.org/schema/pdbx-v50.xsd>
pdbo: <https://rdf.wwpdb.org/schema/pdbx-v50.owl#>
dc: <http://purl.org/dc/elements/1.1/>
skos: <http://www.w3.org/2004/02/skos/core#>
pdb: <https://rdf.wwpdb.org/pdb/>
