- Phenotype:
  - a: amr:PhenotypeMeasurement
  - amr:antibioticName:
    - antibiotic_name: "trimethoprim-sulfamethoxazole"
  - amr:antibioticOntology:
    - antibiotic_ontology: <https://www.ebi.ac.uk/ols4/ontologies/aro/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FARO_3004024>
  - amr:antibioticOntologyId:
    - antibiotic_ontology_id: obo:ARO_3004024
  - amr:assemblyId:
    - assembly_id: <http://identifiers.org/insdc.gca/GCA_001096525.1>
  - amr:astStandard:
    - ast_standard: "CLSI"
  - amr:bioSample:
    - bio_sample: biosample:SAMEA1028830
  - amr:collectionYear:
    - collection_year: 2010
  - amr:country:
    - country: "Thailand"
  - amr:database:
    - database: "CABBAGE_PubMed_data"
  - amr:genus:
    - genus: "Streptococcus"
  - amr:geographicalRegion:
    - geographical_region: "Asia"
  - amr:geographicalSubregion:
    - geographical_subregion: "South-eastern Asia"
  - amr:host:
    - host: "Homo sapiens"
  - amr:isoCountryCode:
    - iso_country_code: "THA"
  - amr:isolateId:
    - isolate_id: "SMRU2695"
  - amr:isolationCategory:
    - isolation_category: "respiratory tract"
  - amr:isolationSource:
    - isolation_source: "nasopharynx"
  - amr:laboratoryTypingMethod:
    - laboratory_typing_method: "disk diffusion"
  - amr:organism:
    - organism: "Streptococcus pneumoniae"
  - amr:resistancePhenotype:
    - resistance_phenotype: "susceptible"
  - amr:species:
    - species: "Streptococcus pneumoniae"
  - amr:sraAccession:
    - sra_accession: sra:ERS022205
  - dct:references:
    - references: <http://rdf.ncbi.nlm.nih.gov/pubmed/24509479>

- Genotype:
  - a: amr:GenotypeFeature
  - amr:amr_class:
    - amr_class: "EFFLUX"
  - amr:amr_element_symbol:
    - amr_element_symbol: "norM"
  - amr:amrSubclass:
    - amr_subclass: "EFFLUX"
  - amr:assemblyId:
    - assembly_id_genotype: sra:ERZ25089697
  - amr:bin:
    - bin: "9363"
  - amr:bioSample:
    - bio_sample_genotype: biosample:SAMEA104147270
  - amr:elementSubtype:
    - element_subtype: "AMR"
  - amr:elementType:
    - element_type: "AMR"
  - amr:evidenceAccession:
    - evidence_accession: "NF000263.1"
  - amr:evidenceDescription:
    - evidence_description: "sodium-coupled multidrug efflux MATE transporter NorM"
  - amr:evidenceLink:
    - evidence_link: <https://www.ncbi.nlm.nih.gov/genome/annotation_prok/evidence/NF000263/>
  - amr:evidenceType:
    - evidence_type: "HMM"
  - amr:featureId:
    - feature_id: "ERZ25089697_00148"
  - amr:geneSymbol:
    - gene_symbol: "mdtK"
  - amr:genus:
    - genus_genotype: "Neisseria"
  - amr:organism:
    - organism_genotype: "Neisseria gonorrhoeae"
  - amr:region:
    - region: "ERZ25089697.1"
  - amr:regionEnd:
    - region_end: 138029
  - amr:regionStart:
    - region_start: 136650
  - amr:species:
    - species_genotype: "Neisseria gonorrhoeae"
  - amr:strand:
    - strand: "-"
  - obo:RO_0002162:
    - in_taxon: <http://identifiers.org/taxonomy/485>
