rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
amr: <http://example.org/ebiamr#>
biosample: <https://identifiers.org/biosample/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
obo_taxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
taxonomy: <http://identifiers.org/taxonomy/>
sra: <https://identifiers.org/insdc.sra/>
gca: <http://identifiers.org/insdc.gca/>
