rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
schema: <http://schema.org/>
dcterms: <http://purl.org/dc/terms/>
xsd: <http://www.w3.org/2001/XMLSchema#>
skos: <http://www.w3.org/2004/02/skos/core#>
massbank: <https://identifiers.org/massbank/>
cas: <https://identifiers.org/cas/>
chebi: <https://identifiers.org/CHEBI/>
kegg: <https://identifiers.org/kegg.compound/>
pubchem: <https://identifiers.org/pubchem.compound/>
inchi: <https://identifiers.org/inchi/>
inchikey: <https://identifiers.org/inchikey/>
chemspider: <https://identifiers.org/chemspider/>
comptox: <https://identifiers.org/comptox/>
obo: <http://purl.obolibrary.org/obo/>
splash: <https://identifiers.org/splash/>
mbo: <http://www.massbank.jp/ontology/>
