title: HomoloGene RDF
website: https://www.ncbi.nlm.nih.gov/homologene/
description: HomoloGene RDF is a translation of HomoloGene data into RDF.
tags: []
provider: National Center for Biotechnology Information
creators:
  - name: Hirokazu Chiba
    affiliation: Database Center for Life Science
version: 2023-03-01
issued: 2023-03-01
licenses:
  - https://www.ncbi.nlm.nih.gov/home/about/policies/
