rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
ncbigene: <http://identifiers.org/ncbigene/>
ncbiprotein: <http://identifiers.org/ncbiprotein/>
homologene: <https://ncbi.nlm.nih.gov/homologene/>
taxid: <http://identifiers.org/taxonomy/>
taxon: <http://ddbj.nig.ac.jp/ontologies/taxonomy/>
orth: <http://purl.org/net/orth#>
