DruMAPAssayMolecule:
  - source("assay_molecules.csv")
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/assay_molecule/$id"
  - variables:
    - drumap_assay_molecule_id: $id
    - drumap_assay_molecule_label: csv("name")
    - drumap_assay_molecule_gene_symbol: csv("gene_symbol")
    - drumap_assay_molecule_gene_id: csv("gene_id")
    - drumap_assay_molecule_species: csv("species")
    - drumap_assay_molecule_description: csv("description")
    - drumap_assay_molecule_assay_organism:
      - csv("assay_organism_id")
      - prepend("https://drumap.nibiohn.go.jp/rdf/assay_organism/")
