DruMAPAssayParameter:
  - source("assay_parameters.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/assay_parameter/$id"
  - objects:
    - drumap_assay_parameter_id: $id
    - drumap_assay_parameter_label: csv("name")
    - drumap_assay_parameter_assay:
      - csv("assay_id")
      - prepend("https://drumap.nibiohn.go.jp/rdf/assay/")
    - drumap_assay_parameter_unit: csv("value")
