rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
skos: <http://www.w3.org/2004/02/skos/core#>
up: <http://purl.uniprot.org/uniprot/>
core: <http://purl.uniprot.org/core/>
intact: <http://purl.uniprot.org/intact/>
enzyme: <http://purl.uniprot.org/enzyme/>
isoform: <http://purl.uniprot.org/isoforms/>
pubmed: <https://pubmed.ncbi.nlm.nih.gov/12775724>
citation: <http://purl.uniprot.org/pubmed/12775724>
range: <http://purl.uniprot.org/range/>
