id: <http://identifiers.org/>
pmid: <http://identifiers.org/pubmed/>
taxonomy: <http://identifiers.org/taxonomy/>
bibo: <http://purl.org/ontology/bibo/>
uniprot: <http://purl.uniprot.org/uniprot/>
qudt: <http://qudt.org/vocab/unit#>
chembl_activity: <http://rdf.ebi.ac.uk/resource/chembl/activity/>
chembl_binding_site: <http://rdf.ebi.ac.uk/resource/chembl/binding_site/>
chembl_assay: <http://rdf.ebi.ac.uk/resource/chembl/assay/>
chembl_document: <http://rdf.ebi.ac.uk/resource/chembl/document/>
chembl_journal: <http://rdf.ebi.ac.uk/resource/chembl/journal/>
chembl_molecule: <http://rdf.ebi.ac.uk/resource/chembl/molecule/>
chembl_protclass: <http://rdf.ebi.ac.uk/resource/chembl/protclass/>
chembl_source: <http://rdf.ebi.ac.uk/resource/chembl/source/>
chembl_target: <http://rdf.ebi.ac.uk/resource/chembl/target/>
chembl_target_cmpt: <http://rdf.ebi.ac.uk/resource/chembl/targetcomponent/>
chembl_drug_mechanism: <http://rdf.ebi.ac.uk/resource/chembl/drug_mechanism/>
chembl_drug_indication: <http://rdf.ebi.ac.uk/resource/chembl/drug_indication/>
chembl_cell_line: <http://rdf.ebi.ac.uk/resource/chembl/cell_line/>
chembl_biocomponent: <http://rdf.ebi.ac.uk/resource/chembl/biocomponent/>
cco: <http://rdf.ebi.ac.uk/terms/chembl#>
schema: <http://schema.org/>
bao: <http://www.bioassayontology.org/bao#>
oboinowl: <http://www.geneontology.org/formats/oboInOwl#>
ops: <http://www.openphacts.org/units/>
uo: <http://purl.obolibrary.org/obo/>
dc: <http://purl.org/dc/elements/1.1/>
dcterms: <http://purl.org/dc/terms/>
cheminf: <http://semanticscience.org/resource/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
skos: <http://www.w3.org/2004/02/skos/core#>
foaf: <http://xmlns.com/foaf/0.1/>
sio: <http://semanticscience.org/resource/>
